import { ExtractionResult } from "./mulkiya-extractor";
import { PassportExtractionResult } from "./passport-extractor";
import { ResidenceExtractionResult } from "./residence-extractor";

export const SAMPLE_MULKIYA_RESULTS: Record<string, ExtractionResult> = {
  dubai_range_rover: {
    success: true,
    data: {
      plate_source: "Dubai",
      plate_category: "Private",
      plate_code: "AA",
      plate_number: "88271",
      vin: "SAL1P9EU2RA165631",
      make: "RANGE ROVER",
      model: "SPORT",
      year: 2024,
      color: "Grey",
      insurance_company: "Adamjee Insurance Company Ltd",
      policy_number: "2510061602",
      insurance_expiry: "2026-07-19",
      registration_expiry: "2026-06-19",
      registration_issuance: "2025-04-28",
    },
    confidence: {
      vin: 0.99,
      plate_number: 0.98,
      plate_source: 0.99,
      make: 0.96,
      year: 0.95,
      insurance_company: 0.92,
      registration_expiry: 0.97,
    },
    warnings: [],
    raw_lines_count: 24,
    raw_text: `United Arab Emirates - Dubai RTA Vehicle License\nTraffic Plate No. AA / 88271 دبي مصدر اللوحة\nPlate Category Private خصوصي صنف اللوحة\nExp. Date 19/06/2026 Reg. Date 28/04/2025\nIns. Exp. 19/07/2026 مؤمنة لدى Adamjee Insurance\nPolicy No. 2510061602 نوع التأمين شامل\nModel 2024 لون المركبة رمادي\nVeh. Type RANGE ROVER SPORT\nChassis No. SAL1P9EU2RA165631`,
  },
  abu_dhabi_mercedes: {
    success: true,
    data: {
      plate_source: "Abu Dhabi",
      plate_category: "Private",
      plate_code: "5",
      plate_number: "19283",
      vin: "W1N0G8DB8PF912345",
      make: "MERCEDES-BENZ",
      model: "G 63 AMG",
      year: 2025,
      color: "Black",
      insurance_company: "Sukoon Insurance PJSC",
      policy_number: "9823410921",
      insurance_expiry: "2026-11-15",
      registration_expiry: "2026-10-15",
      registration_issuance: "2025-10-15",
    },
    confidence: {
      vin: 0.99,
      plate_number: 0.99,
      plate_source: 0.99,
      make: 0.98,
      year: 0.97,
      insurance_company: 0.94,
      registration_expiry: 0.98,
    },
    warnings: [],
    raw_lines_count: 26,
    raw_text: `United Arab Emirates - Abu Dhabi Police\nPlate No. 5 / 19283 أبوظبي خصوصي\nMercedes-Benz G63 AMG 2025\nVIN: W1N0G8DB8PF912345\nColor: Black أسود\nReg. Exp: 15/10/2026 Ins. Exp: 15/11/2026\nInsurer: Sukoon Insurance PJSC Policy: 9823410921`,
  },
};

export const SAMPLE_PASSPORT_RESULTS: Record<string, PassportExtractionResult> = {
  sample_passport_uk: {
    success: true,
    data: {
      passport_number: "984210543",
      first_name: "ALEXANDER JAMES",
      last_name: "DAVIES",
      full_name: "ALEXANDER JAMES DAVIES",
      nationality_code: "GBR",
      nationality_name: "United Kingdom",
      issuing_country: "United Kingdom",
      date_of_birth: "1992-05-14",
      gender: "M",
      issue_date: "2021-08-20",
      expiry_date: "2031-08-20",
      mrz_lines: [
        "P<GBRDAVIES<<ALEXANDER<JAMES<<<<<<<<<<<<<<<<",
        "9842105434GBR9205142M3108208<<<<<<<<<<<<<<02",
      ],
      mrz_valid: true,
      status: "VALID",
    },
    confidence: {
      passport_number: 0.99,
      full_name: 0.98,
      nationality: 0.99,
      expiry_date: 0.98,
    },
    warnings: [],
    raw_lines_count: 18,
    raw_text: `BRITISH PASSPORT\nSurname: DAVIES\nGiven Names: ALEXANDER JAMES\nNationality: BRITISH CITIZEN\nDate of Birth: 14 MAY /MAI 92\nSex: M\nPlace of Birth: LONDON\nDate of Issue: 20 AUG /AOU 21\nDate of Expiry: 20 AUG /AOU 31\nAuthority: HMPO\nP<GBRDAVIES<<ALEXANDER<JAMES<<<<<<<<<<<<<<<<\n9842105434GBR9205142M3108208<<<<<<<<<<<<<<02`,
  },
};

export const SAMPLE_RESIDENCE_RESULTS: Record<string, ResidenceExtractionResult> = {
  sample_residence_uae: {
    success: true,
    emirates_id: {
      id_number: "784-1990-1284729-3",
      name_en: "MOHAMMED RASHID AL MAKTOUM",
      name_ar: "محمد راشد المكتوم",
      nationality: "United Arab Emirates",
      date_of_birth: "1990-04-12",
      issue_date: "2023-05-10",
      expiry_date: "2028-05-09",
      card_number: "019284712",
      status: "VALID",
    },
    driving_licence: {
      licence_number: "7192834",
      traffic_code_no: "51829304",
      issued_by: "Dubai (RTA)",
      issue_date: "2022-06-15",
      expiry_date: "2027-06-14",
      categories: ["Light Vehicle (3)"],
      status: "VALID",
    },
    reconciliation: {
      name_match: true,
      nationality_match: true,
      all_valid: true,
      overall_status: "VERIFIED",
      review_reasons: [],
    },
    confidence: {
      emirates_id_number: 0.99,
      name_en: 0.98,
      name_ar: 0.97,
      dl_licence_number: 0.99,
      dl_issued_by: 0.99,
    },
    warnings: [],
    raw_lines_count: 32,
    raw_text: `UNITED ARAB EMIRATES\nFederal Authority for Identity and Citizenship\nResident Identity Card\nID Number: 784-1990-1284729-3\nName: MOHAMMED RASHID AL MAKTOUM\nالاسم: محمد راشد المكتوم\nNationality: United Arab Emirates\nExpiry Date: 09/05/2028\n\nDUBAI ROADS & TRANSPORT AUTHORITY\nDriving Licence رخصة قيادة\nLicence No: 7192834\nT.C. No: 51829304 الرمز المروري\nIssue Date: 15/06/2022\nExpiry Date: 14/06/2027\nClass: 3 - Light Vehicle مركبة خفيفة`,
  },
};
